import arcpy
#script must be run in Python 2.7

#Define tables to update - using complete sde connection string
unit=r"C:\Users\marthajensen\AppData\Roaming\ESRI\Desktop10.7\ArcCatalog\sde@ugshazards.sde\ugshazards.sde.borehole_unit_table"
sample=r"C:\Users\marthajensen\AppData\Roaming\ESRI\Desktop10.7\ArcCatalog\sde@ugshazards.sde\ugshazards.sde.borehole_sample_table"
borehole=r"C:\Users\marthajensen\AppData\Roaming\ESRI\Desktop10.7\ArcCatalog\sde@ugshazards.sde\ugshazards.sde.borehole_locations"

#Truncate existing tables
arcpy.TruncateTable_management(in_table=unit)
arcpy.TruncateTable_management(in_table=sample)
arcpy.TruncateTable_management(in_table=borehole)
print ("Finished truncating all data, starting to append new records")

#################################################APPEND##########################################

#Append data to existing tables - using tables Gordon created (change inputs here if needed-highly likely you will need to change the gdb name because they are usually not overwritten)
#inputs
newborehole="'G:/Shared drives/UGS_Hazards_Geotech/Geotechnical Database/Borehole_Data_WGS84_20210225.gdb/Borehole_Locations'"
newsample="'G:/Shared drives/UGS_Hazards_Geotech/Geotechnical Database/Borehole_Data_WGS84_20210225.gdb/Sample_Table'"
newunit="'G:/Shared drives/UGS_Hazards_Geotech/Geotechnical Database/Borehole_Data_WGS84_20210225.gdb/Unit_Table'"

arcpy.Append_management(inputs=newborehole, target=borehole, schema_type="NO_TEST", field_mapping='boreid "BoreID" true true false 8000 Text 0 0 ,First,#,newborehole,boreid,-1,-1;ugs_gdid "UGS_GDID" true true false 4 Long 0 10 ,First,#,newborehole,ugs_gdid,-1,-1;consultant "Consultant" true true false 8000 Text 0 0 ,First,#,newborehole,consultant,-1,-1;projectid "ProjectID" true true false 8000 Text 0 0 ,First,#,newborehole,projectid,-1,-1;udot_pin "UDOT_PIN" true true false 4 Long 0 10 ,First,#,newborehole,udot_pin,-1,-1;project_name "Project_Name" true true false 8000 Text 0 0 ,First,#,newborehole,project_name,-1,-1;latitude "Latitude" true true false 8000 Text 0 0 ,First,#,newborehole,latitude,-1,-1;longitude "Longitude" true true false 8 Double 8 38 ,First,#,newborehole,longitude,-1,-1;coordinate_source "Coordinate_Source" true true false 8000 Text 0 0 ,First,#,newborehole,coordinate_source,-1,-1;elevation_ft "Elevation_Ft" true true false 8 Double 8 38 ,First,#,newborehole,elevation_ft,-1,-1;elevation_source "Elevation_Source" true true false 8000 Text 0 0 ,First,#,newborehole,elevation_source,-1,-1;date_completed "Date_Completed" true true false 8 Date 0 0 ,First,#,newborehole,date_completed,-1,-1;geologic_unit "Geologic_Unit" true true false 8000 Text 0 0 ,First,#,newborehole,geologic_unit,-1,-1;exploration_type "Exploration_Type" true true false 8000 Text 0 0 ,First,#,newborehole,exploration_type,-1,-1;exploration_method "Exploration_Method" true true false 8000 Text 0 0 ,First,#,newborehole,exploration_method,-1,-1;exploration_equiptment "Exploration_Equiptment" true true false 8000 Text 0 0 ,First,#,newborehole,exploration_equipment,-1,-1;gw_depth "GW_Depth" true true false 8 Double 8 38 ,First,#,newborehole,gw_depth,-1,-1;hammer_type "Hammer_Type" true true false 8000 Text 0 0 ,First,#,newborehole,hammer_type,-1,-1;correctedn1_60 "CorrectedN1_60" true true false 8000 Text 0 0 ,First,#,newborehole,correctn1_60,-1,-1;completion "Completion" true true false 8000 Text 0 0 ,First,#,newborehole,completion,-1,-1;bedrock_refusal "Bedrock_Refusal" true true false 4 Long 0 10 ,First,#,newborehole,bedrock_refusal,-1,-1;enteredby "EnteredBy" true true false 8000 Text 0 0 ,First,#,newborehole,enteredby,-1,-1;notes "Notes" true true false 8000 Text 0 0 ,First,#,newborehole,notes,-1,-1;report_url "report_url" true true false 100 Text 0 0 ,First,#,newborehole,report_url,-1,-1;globalid "globalid" false false false 38 GlobalID 0 0 ,First,#;databasedate "databasedate" true true false 8 Date 0 0 ,First,#,newborehole,databasedate,-1,-1', subtype="")
arcpy.Append_management(inputs=newsample, target=sample, schema_type="NO_TEST", field_mapping='boreid "BoreID" true true false 8000 Text 0 0 ,First,#,newsample,boreid,-1,-1;samplenumber "SampleNumber" true true false 4 Long 0 10 ,First,#,newsample,samplenumber,-1,-1;sampleupperdepth "SampleUpperDepth" true true false 8 Double 8 38 ,First,#,newsample,sampleupperdepth,-1,-1;samplelower_depth "SampleLower Depth" true true false 8 Double 8 38 ,First,#,newsample,samplelower_depth,-1,-1;samplemethod "SampleMethod" true true false 8000 Text 0 0 ,First,#,newsample,samplemethod,-1,-1;nvalue "Nvalue" true true false 4 Long 0 10 ,First,#,newsample,nvalue,-1,-1;classification "Classification" true true false 8000 Text 0 0 ,First,#,newsample,classification,-1,-1;gravel_percent "Gravel_Percent" true true false 4 Long 0 10 ,First,#,newsample,gravel_percent,-1,-1;sand_percent "Sand_Percent" true true false 4 Long 0 10 ,First,#,newsample,sand_percent,-1,-1;fines_percent "Fines_Percent" true true false 4 Long 0 10 ,First,#,newsample,fines_percent,-1,-1;labmoisture_percent "LabMoisture_Percent" true true false 8 Double 8 38 ,First,#,newsample,labmoisture_percent,-1,-1;labdrydensity_pcf "LabDryDensity_pcf" true true false 8 Double 8 38 ,First,#,newsample,labdrydensity_pcf,-1,-1;ll "LL" true true false 8000 Text 0 0 ,First,#,newsample,ll,-1,-1;pl "PL" true true false 8000 Text 0 0 ,First,#,newsample,pl,-1,-1;pi "PI" true true false 8000 Text 0 0 ,First,#,newsample,pi,-1,-1;sct_percent "SCT_Percent" true true false 8 Double 8 38 ,First,#,newsample,sct_percent,-1,-1;sct_dry_percent "SCT_Dry_Percent" true true false 8 Double 8 38 ,First,#,newsample,sct_dry_percent,-1,-1;shear_type "Shear_Type" true true false 8000 Text 0 0 ,First,#,newsample,shear_type,-1,-1;shearangle_degree "ShearAngle_Degree" true true false 8000 Text 0 0 ,First,#,newsample,shearangle_degree,-1,-1;shearcohesion_psi "ShearCohesion_PSI" true true false 8000 Text 0 0 ,First,#,newsample,shearcohesion_psi,-1,-1;resistivity_ohm_cm "Resistivity_ohm_cm" true true false 8000 Text 0 0 ,First,#,newsample,resistivity_ohm_cm,-1,-1;sulfates_ppm "Sulfates_ppm" true true false 8000 Text 0 0 ,First,#,newsample,sulfates_ppm,-1,-1;chlorides_ppm "Chlorides_ppm" true true false 8000 Text 0 0 ,First,#,newsample,chlorides_ppm,-1,-1;organics_percent_weight "Organics_Percent_Weight" true true false 8000 Text 0 0 ,First,#,newsample,organics_percent_weight,-1,-1;ph "pH" true true false 8000 Text 0 0 ,First,#,newsample,ph,-1,-1;notes "Notes" true true false 8000 Text 0 0 ,First,#,newsample,notes,-1,-1', subtype="")
arcpy.Append_management(inputs=newunit, target=unit, schema_type="NO_TEST", field_mapping='boreid "BoreID" true true false 8000 Text 0 0 ,First,#,newunit,boreid,-1,-1;upperdepth "UpperDepth" true true false 8 Double 8 38 ,First,#,newunit,upperdepth,-1,-1;lowerdepth "LowerDepth" true true false 8 Double 8 38 ,First,#,newunit,lowerdepth,-1,-1;uscs "USCS" true true false 8000 Text 0 0 ,First,#,newunit,uscs,-1,-1;unitname "UnitName" true true false 8000 Text 0 0 ,First,#,newunit,unitname,-1,-1;fieldmoisture "FieldMoisture" true true false 8000 Text 0 0 ,First,#,newunit,fieldmoisture,-1,-1;fieldcolor "FieldColor" true true false 8000 Text 0 0 ,First,#,newunit,fieldcolor,-1,-1;fielddensity "FieldDensity" true true false 8000 Text 0 0 ,First,#,newunit,fielddensity,-1,-1;fieldconsistency "FieldConsistency" true true false 8000 Text 0 0 ,First,#,newunit,fieldconsistency,-1,-1;notes "Notes" true true false 8000 Text 0 0 ,First,#,newunit,notes,-1,-1', subtype="")

print ("Finished appending new records")

# Get count of points in feature class
count=arcpy.GetCount_management(in_rows=borehole)

print ("The count of borehole locations is now " + str(count))